export const events = [
  {
    id: 1,
    date: new Date(),
    start: 4,
    end: 20,
    day: 0,
    user: "#4185d8",
    title: "Condominio Bureau",
  },
  {
    id: 4,
    date: new Date(),
    start: 7,
    end: 14,
    day: 0,
    user: "#4185d8",
    title: "Condominio Bureau",
  },
  {
    id: 5,
    date: new Date(),
    start: 22,
    end: 28,
    day: 0,
    user: "#4185d8",
    title: "Condominio Bureau",
  },
  {
    id: 2,
    date: new Date(),
    start: 9,
    end: 15,
    day: 4,
    user: "#4185d8",
    title: "Condominio Bureau",
  },
  {
    id: 3,
    date: new Date(),
    start: 7,
    end: 13,
    day: 4,
    user: "#4185d8",
    title: "Portão Bruno",
  },
]