export const events = [
  {
    id: 53,
    date: new Date(),
    start: 2,
    end: 7,
    day: 0,
    user: "#1af1a1",
    title: "Hotel California",
  },
  {
    id: 51,
    date: new Date(),
    start: 2,
    end: 7,
    day: 0,
    user: "#fff111",
    title: "Hotel California",
  },
  {
    id: 1,
    date: new Date(),
    start: 4,
    end: 9,
    day: 0,
    user: "#aaafff",
    title: "Hotel Benfica",
  },
  {
    id: 40,
    date: new Date(),
    start: 3,
    end: 20,
    day: 0,
    user: "#4185d8",
    title: "Condominio Jonas",
  },
  {
    id: 4,
    date: new Date(),
    start: 4,
    end: 7,
    day: 0,
    user: "#f185d8",
    title: "Condominio Japa",
  },
  {
    id: 42,
    date: new Date(),
    start: 4,
    end: 12,
    day: 0,
    user: "#f185d8",
    title: "a",
  },
  // // {
  // //   id: 40,
  // //   date: new Date(),
  // //   start: 4,
  // //   end: 20,
  // //   day: 0,
  // //   user: "#4185d8",
  // //   title: "b",
  // // },
  // {
  //   id: 41,
  //   date: new Date(),
  //   start: 4,
  //   end: 25,
  //   day: 0,
  //   user: "#4185d8",
  //   title: "Marcos",
  // },
  // {
  //   id: 5,
  //   date: new Date(),
  //   start: 26,
  //   end: 28,
  //   day: 0,
  //   user: "#4185d8",
  //   title: "Condominio Bureau",
  // },
  // {
  //   id: 3,
  //   date: new Date(),
  //   start: 7,
  //   end: 13,
  //   day: 0,
  //   user: "#4185d8",
  //   title: "Portão Bruno",
  // },
  // {
  //   id: 2,
  //   date: new Date(),
  //   start: 9,
  //   end: 15,
  //   day: 4,
  //   user: "#4185d8",
  //   title: "Condominio Tanide",
  // },
]